Update upload-to-zenodo.yml

diff --git a/.github/workflows/upload-to-zenodo.yml b/.github/workflows/upload-to-zenodo.yml
--- a/.github/workflows/upload-to-zenodo.yml
+++ b/.github/workflows/upload-to-zenodo.yml
@@ -14,19 +14,15 @@ jobs:
       - name: Install curl and jq
         run: sudo apt-get install -y curl jq
 
-      - name: Remove Existing Files from Draft
+      - name: Discard Current Draft
         run: |
-          # Get the list of files in the current draft deposition
-          files_response=$(curl -s -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
-                                  "https://zenodo.org/api/deposit/depositions/${{ secrets.ZENODO_DEPOSITION_ID }}/files")
-          echo "Files Response: $files_response"
-          
-          # Extract file IDs and delete each one
-          for file_id in $(echo "$files_response" | jq -r '.[].id'); do
-            echo "Removing file ID: $file_id"
-            curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
-                  "https://zenodo.org/api/deposit/depositions/${{ secrets.ZENODO_DEPOSITION_ID }}/files/$file_id"
-          done
+          discard_response=$(curl -s -X POST -H "Authorization: Bearer ${{ secrets.ZENODO_ACCESS_TOKEN }}" \
+                              "https://zenodo.org/api/deposit/depositions/${{ secrets.ZENODO_DEPOSITION_ID }}/actions/discard")
+          echo "Discard Response: $discard_response"
+          if echo "$discard_response" | grep -q '"status": 403'; then
+            echo "Failed to discard the draft. The draft might be locked or in an invalid state."
+            exit 1
+          fi
 
       - name: Create a New Version of the Deposition
         id: new_version
